theme: minima
lang: zh
author: Mayx
email: mayx@outlook.com
title: Mayx日报
url: https://mayx.tk
description: >
  由于Mayx懒得发东西而使用Travis-CI自动更新的日报系统

github_username: Mabbs
rss: rss
show_excerpts: true
excerpt_separator: <!--more-->

header_pages:
 - about.md
 - site.md

plugins:
  - jekyll-sitemap
  - jekyll-feed
feed:
  path: feed.xml
